<?php
/**
 * Created by PhpStorm.
 * User: oabroms
 * Date: 10/6/17
 * Time: 4:37 PM
 */

namespace Castlebranch\Siesta;


use Castlebranch\Siesta\Controller;

class ControTest extends Controller
{
    public $statusCode = 220;
public function getStatusCode()
{
    return parent::getStatusCode(); // TODO: Change the autogenerated stub
}
public function setStatusCode($statusCode)
{
    return parent::setStatusCode($statusCode); // TODO: Change the autogenerated stub
}

public function respondWithArray(array $data, array $headers = [])
{
    return parent::respondWithArray($data, $headers); // TODO: Change the autogenerated stub
}
public function respondWithNoContent()
{
    return parent::respondWithNoContent(); // TODO: Change the autogenerated stub
}
public function respondWithAccepted($data)
{
    return parent::respondWithAccepted($data); // TODO: Change the autogenerated stub
}
public function respondWithCreated($data)
{
    return parent::respondWithCreated($data); // TODO: Change the autogenerated stub
}
}