<?php

namespace Castlebranch\Siesta;

use Castlebranch\Siesta\Request;
use Illuminate\Contracts\Validation\Validator;

class RequestInstance extends Request
{

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function response(array $errors)
    {
        return parent::response($errors); // TODO: Change the autogenerated stub
    }

    public function failedValidation(Validator $validator)
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}